std_msgs/Header header

int64 input_id

builtin_interfaces/Time[] stamps

geometry_msgs/Point[] position
geometry_msgs/Quaternion[] orientation
geometry_msgs/Vector3[] attitude_rate
geometry_msgs/Vector3[] velocity
geometry_msgs/Vector3[] acceleration
geometry_msgs/Vector3[] jerk

float64[] heading
float64[] heading_rate
float64[] heading_acceleration
float64[] heading_jerk

uint8 use_orientation
uint8 use_attitude_rate