# A service to delete a model in a Gazebo simulation
# using the mrs_gazebo_ros_interface package.

# Name of the model to be deleted.
string model_name

---

# Indicates whether the requested operation was carried out successfully.
bool ok
