# A service to apply a force and/or torque to a link in a Gazebo simulation
# using the mrs_gazebo_ros_interface package.

# Name of the model, containing the link to apply the force/torque to.
string model_name

# Name of the link to apply the force/torque to.
string link_name

# The force vector to apply (in the Gazebo global coordinate system).
float64[3] force

# The torque vector to apply (in the Gazebo global coordinate system).
float64[3] torque

---

# Indicates whether the requested operation was carried out successfully.
bool ok
