# A service to apply a force and/or torque to a link in a Gazebo simulation
# using the mrs_gazebo_ros_interface package. The links will be joined
# by a revolute joint type.

# Name of the model, containing the first link to be joined.
string model_name_1

# Name the first link to be joined.
string link_name_1

# Name of the model, containing the second link to be joined.
string model_name_2

# Name of the second link to be joined.
string link_name_2

---

# Indicates whether the requested operation was carried out successfully.
bool ok
