std_msgs/Header header

geometry_msgs/Point position
geometry_msgs/Point velocity
geometry_msgs/Point acceleration
geometry_msgs/Point jerk
geometry_msgs/Point snap

float64 heading
float64 heading_rate

geometry_msgs/Point attitude_rate

bool disable_position_gains

uint8 use_position_horizontal
uint8 use_position_vertical

uint8 use_velocity_horizontal
uint8 use_velocity_vertical

uint8 use_acceleration
uint8 use_jerk
uint8 use_snap
uint8 use_attitude_rate
uint8 use_heading
uint8 use_heading_rate
