#!/bin/bash
set -e

# Path to the flattened interfaces in the build folder (passed as $1)
BUILD_INTERFACES=$1

# Identify the package root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PKG_ROOT="$(dirname "$SCRIPT_DIR")"

# Create a unique temporary staging directory to avoid naming collisions
STAGING_DIR=$(mktemp -d -t mrs_msgs_docs_XXXXXX)

# Function to ensure the unique temporary directory is deleted on exit
cleanup() {
    if [ -d "$STAGING_DIR" ]; then
        rm -rf "$STAGING_DIR"
    fi
}

# Register cleanup to run even if the script is interrupted or fails
trap cleanup EXIT

# Verify that interfaces were already generated by CMake
if [ ! -d "$BUILD_INTERFACES" ]; then
    echo "Error: Build directory not found at $BUILD_INTERFACES"
    exit 1
fi

# Copy Metadata
cp "$PKG_ROOT/package.xml" "$STAGING_DIR/"
cp "$PKG_ROOT/rosdoc2.yaml" "$STAGING_DIR/"
cp "$PKG_ROOT/README.md" "$STAGING_DIR/"
cp "$PKG_ROOT/LICENSE" "$STAGING_DIR/"

# Copy all subdirectories (msg, srv, action, etc.) from build_interfaces
for dir in "$BUILD_INTERFACES"/*/; do
    if [ -d "$dir" ]; then
        cp -rL "$dir" "$STAGING_DIR/"
    fi
done

# remove all images because docs are broken otherwise
sed -i '/!\[.*\](.*)/d' "$STAGING_DIR/README.md"

# Run rosdoc2 against the staging area and save output to the source 'doc' folder
rosdoc2 build --package-path "$STAGING_DIR" --output-directory "$PKG_ROOT/doc"

echo "Success: Docs generated in $PKG_ROOT/doc"
