# True if the MPC-tracker-based collision avoidance is active
bool collision_avoidance_enabled

# True if the MPC-tracker-based collision avoidance is engaged to avoid collision with other UAV
bool avoiding_collision

# True if the bumper is active
bool bumper_active

# Names of other robots currently visible to the MPC-tracker-based collision avoidance system, if any.
string[] other_robots_visible
