name: docs

on:
  push:
    branches: [ ros2 ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build documentation
        run: ./.ci/ci_generate_docs.sh

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./doc/html

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/ros2'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
